### ISSUE TITLE
Not seeing any download stats for python 3.10

### ISSUE THREAD

**Issue by jaingaurav** [sophiamyang/condastats#13]
* condastats version: 0.2.1
* Python version: 3.10.6
* Operating System: OS X

### Description

I am not seeing any download stats for python 3.10. Based on the numbers it looks like 3.10 may be accounted towards 3.1.

### What I Did

```
# condastats pkg_python pandas --start_month=2022-07 --end_month=2022-07
pkg_name  pkg_python
pandas    3.6           255104
          3.8           449448
          3.9           482697
          2.7            27661
          3.5            39544
          3.7           701528
          3.1           155171
          3.3              388
          3.4             1321
          2.6              588
Name: counts, dtype: int64
```

**Comment by sophiamyang** [comment]
Thanks for reporting the issue! That's a very good question. @seibert @cappadona I actually don't see 3.10 in our database. Could you please help check?

**Comment by cappadona** [comment]
Nice catch. Looks like the regex is limiting  `pkg_python` to a length of two. I will correct this is the new pipeline and we can discuss how we want to address the legacy pipeline.
