### ISSUE TITLE
How to get download stats from a package in a conda channel?

### ISSUE THREAD

**Issue by grantbuster** [sophiamyang/condastats#7]
* condastats version: v0.1.5
* Python version: 3.9.6
* Operating System: ubuntu 20.04 lts

### Description

I've successfully used the condastats cli to get download data from common packages like pandas, but I can't seem to figure out how to download stats from a personal organization / channel. I'm trying to get stats for the conda package: https://anaconda.org/NREL/nrel-rev

### What I Did

These commands work successfully for me:

```
condastats overall pandas
condastats overall --data_source anaconda package pandas
```

But these commands all return an empty series:

```
condastats overall nrel-rev
condastats overall --data_source nrel package nrel-rev
condastats overall --data_source NREL package nrel-rev
```

Is there some secret incantation I'm missing?

**Comment by sophiamyang** [comment]
Hi, sorry for my reply. The NREL channel is not available on the Anaconda public package data. If you are the author of the channel, you may request this channel be added to the Anaconda public data: https://github.com/ContinuumIO/anaconda-package-data.
